In [1]:
import numpy as np
import math
import pandas 
import random 
import time
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn import preprocessing

In [2]:
dataframe = pandas.read_csv("energy_efficiency_data.csv")

dataframe.columns = ['relative_compactness', 'surface_area', 
                     'wall_area', 'roof_area', 'overall_height', 
                     'orientation', 'glazing_area', 
                     'glazing_area_distribution', 'heating_load', 
                     'cooling_load']

In [3]:
print(dataframe.head())

   relative_compactness  surface_area  wall_area  roof_area  overall_height  \
0                  0.98         514.5      294.0     110.25             7.0   
1                  0.98         514.5      294.0     110.25             7.0   
2                  0.98         514.5      294.0     110.25             7.0   
3                  0.90         563.5      318.5     122.50             7.0   
4                  0.90         563.5      318.5     122.50             7.0   

   orientation  glazing_area  glazing_area_distribution  heating_load  \
0          2.0           0.0                        0.0         15.55   
1          4.0           0.0                        0.0         15.55   
2          5.0           0.0                        0.0         15.55   
3          2.0           0.0                        0.0         20.84   
4          3.0           0.0                        0.0         21.46   

   cooling_load  
0         21.33  
1         21.33  
2         21.33  
3         28.2

In [4]:
print(dataframe.describe())

       relative_compactness  surface_area   wall_area   roof_area  \
count            768.000000    768.000000  768.000000  768.000000   
mean               0.764167    671.708333  318.500000  176.604167   
std                0.105777     88.086116   43.626481   45.165950   
min                0.620000    514.500000  245.000000  110.250000   
25%                0.682500    606.375000  294.000000  140.875000   
50%                0.750000    673.750000  318.500000  183.750000   
75%                0.830000    741.125000  343.000000  220.500000   
max                0.980000    808.500000  416.500000  220.500000   

       overall_height  orientation  glazing_area  glazing_area_distribution  \
count       768.00000   768.000000    768.000000                  768.00000   
mean          5.25000     3.500000      0.234375                    2.81250   
std           1.75114     1.118763      0.133221                    1.55096   
min           3.50000     2.000000      0.000000              

In [5]:
print("Shape:", dataframe.shape)

Shape: (768, 10)


In [6]:
print("Data Types:", dataframe.dtypes)

Data Types: relative_compactness         float64
surface_area                 float64
wall_area                    float64
roof_area                    float64
overall_height               float64
orientation                  float64
glazing_area                 float64
glazing_area_distribution    float64
heating_load                 float64
cooling_load                 float64
dtype: object


In [7]:
print("Correlation:", dataframe.corr(method='pearson'))

Correlation:                            relative_compactness  surface_area     wall_area  \
relative_compactness               1.000000e+00 -9.919015e-01 -2.037817e-01   
surface_area                      -9.919015e-01  1.000000e+00  1.955016e-01   
wall_area                         -2.037817e-01  1.955016e-01  1.000000e+00   
roof_area                         -8.688234e-01  8.807195e-01 -2.923165e-01   
overall_height                     8.277473e-01 -8.581477e-01  2.809757e-01   
orientation                        1.712426e-17  1.203260e-17  0.000000e+00   
glazing_area                      -3.209966e-18  3.631399e-17  1.036064e-17   
glazing_area_distribution          2.161659e-17 -2.419423e-16  0.000000e+00   
heating_load                       6.222722e-01 -6.581202e-01  4.556712e-01   
cooling_load                       6.343391e-01 -6.729989e-01  4.271170e-01   

                              roof_area  overall_height   orientation  \
relative_compactness      -8.688234e-01    8

In [8]:
print(dataframe.values)

[[9.800e-01 5.145e+02 2.940e+02 ... 0.000e+00 1.555e+01 2.133e+01]
 [9.800e-01 5.145e+02 2.940e+02 ... 0.000e+00 1.555e+01 2.133e+01]
 [9.800e-01 5.145e+02 2.940e+02 ... 0.000e+00 1.555e+01 2.133e+01]
 ...
 [6.600e-01 7.595e+02 3.185e+02 ... 5.000e+00 1.492e+01 1.755e+01]
 [6.400e-01 7.840e+02 3.430e+02 ... 5.000e+00 1.819e+01 2.021e+01]
 [6.200e-01 8.085e+02 3.675e+02 ... 5.000e+00 1.648e+01 1.661e+01]]


In [9]:
#shuffle
dataset = np.array(dataframe.values)
dataset_shuf = []
index_shuf = list(range(len(dataset)))
random.shuffle(index_shuf)
for i in index_shuf:
    dataset_shuf.append(dataset[i,:])   
dataset_shuf = np.array(dataset_shuf)
dataset_shuf.reshape(768,10)

array([[6.600e-01, 7.595e+02, 3.185e+02, ..., 1.000e+00, 1.318e+01,
        1.619e+01],
       [6.400e-01, 7.840e+02, 3.430e+02, ..., 2.000e+00, 1.684e+01,
        2.056e+01],
       [6.600e-01, 7.595e+02, 3.185e+02, ..., 5.000e+00, 1.134e+01,
        1.481e+01],
       ...,
       [7.600e-01, 6.615e+02, 4.165e+02, ..., 5.000e+00, 3.321e+01,
        3.435e+01],
       [7.400e-01, 6.860e+02, 2.450e+02, ..., 3.000e+00, 1.422e+01,
        1.539e+01],
       [8.200e-01, 6.125e+02, 3.185e+02, ..., 4.000e+00, 2.380e+01,
        2.461e+01]])

In [10]:
X_train = dataset_shuf[:576,0:8]
Y_train = dataset_shuf[:576,8:9]
X_train.reshape(576,8)
Y_train.reshape(576,1)

X_test = dataset_shuf[576:,0:8]
Y_test = dataset_shuf[576:,8:9]
X_test.reshape(192,8)
Y_test.reshape(192,1)

array([[19.68],
       [12.93],
       [ 8.5 ],
       [25.7 ],
       [ 8.45],
       [32.15],
       [13.02],
       [32.75],
       [39.81],
       [31.89],
       [13.17],
       [28.31],
       [24.24],
       [12.19],
       [13.04],
       [12.63],
       [10.14],
       [10.71],
       [33.08],
       [40.68],
       [39.97],
       [32.05],
       [10.55],
       [34.24],
       [12.49],
       [28.63],
       [39.97],
       [28.93],
       [14.65],
       [23.84],
       [32.69],
       [42.96],
       [23.87],
       [10.66],
       [24.29],
       [29.91],
       [33.27],
       [28.75],
       [12.2 ],
       [ 6.05],
       [12.97],
       [ 6.4 ],
       [12.3 ],
       [35.01],
       [16.83],
       [12.76],
       [15.16],
       [38.89],
       [11.13],
       [ 6.77],
       [10.38],
       [36.96],
       [16.86],
       [42.11],
       [14.62],
       [28.37],
       [19.48],
       [11.67],
       [41.32],
       [15.2 ],
       [32.52],
       [32.31],
       [

In [11]:
#one-hot
transformer = ColumnTransformer([('one_hot_encoder', OneHotEncoder(), [5,7])],remainder='passthrough')
X_train = np.array(transformer.fit_transform(X_train), dtype=np.float)

X_test = np.array(transformer.fit_transform(X_test), dtype=np.float)



C:\Users\YaShu\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\YaShu\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you us

In [12]:
pandas.DataFrame(X_train)

0    1    2    3    4    5    6    7    8    9     10     11     12  \
0    0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.66  759.5  318.5   
1    0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.64  784.0  343.0   
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.66  759.5  318.5   
3    0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.71  710.5  269.5   
4    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.98  514.5  294.0   
5    0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.74  686.0  245.0   
6    0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.82  612.5  318.5   
7    0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.62  808.5  367.5   
8    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.71  710.5  269.5   
9    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.74  686.0  245.0   
10   0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.62  808.5  367.5   
11   0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.62  808.5  367.5   
12   0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.79  637.0  343.0   
13   0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.82  612.5  318.5   
14   0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.76  661.5  416.5   
15   1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.98  514.5  294.0   
16   0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.66  759.5  318.5   
17   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.90  563.5  318.5   
18   0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.71  710.5  269.5   
19   0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.71  710.5  269.5   
20   0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.64  784.0  343.0   
21   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.98  514.5  294.0   
22   1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.66  759.5  318.5   
23   0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.86  588.0  294.0   
24   0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.66  759.5  318.5   
25   1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.76  661.5  416.5   
26   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.79  637.0  343.0   
27   1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.66  759.5  318.5   
28   0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.82  612.5  318.5   
29   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.98  514.5  294.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...    ...    ...   
546  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.79  637.0  343.0   
547  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.79  637.0  343.0   
548  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.62  808.5  367.5   
549  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.90  563.5  318.5   
550  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.82  612.5  318.5   
551  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.98  514.5  294.0   
552  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.82  612.5  318.5   
553  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.76  661.5  416.5   
554  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.86  588.0  294.0   
555  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.69  735.0  294.0   
556  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.90  563.5  318.5   
557  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.69  735.0  294.0   
558  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.69  735.0  294.0   
559  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.69  735.0  294.0   
560  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.79  637.0  343.0   
561  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.69  735.0  294.0   
562  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.69  735.0  294.0   
563  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.69  735.0  294.0   
564  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.66  759.5  318.5   
565  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.74  686.0  245.0   
56

In [13]:
#標準化
X_scaled = np.copy(X_train[:,10:16])
X_scaled2 = np.copy(X_test[:,10:16])

scaler = preprocessing.StandardScaler().fit(X_scaled)

X_scaled = scaler.transform(X_scaled)
X_scaled2 = scaler.transform(X_scaled2)


In [14]:
X_train = np.copy(X_train[:,0:10])
X_test = np.copy(X_test[:,0:10])
X_train = np.append(X_train, X_scaled, axis = 1)
X_test = np.append(X_test, X_scaled2, axis = 1)

pandas.DataFrame(X_train)

0    1    2    3    4    5    6    7    8    9         10        11  \
0    0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0 -0.958867  0.965166   
1    0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 -1.147015  1.241339   
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 -0.958867  0.965166   
3    0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0 -0.488498  0.412821   
4    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  2.051495 -1.796561   
5    0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0 -0.206276  0.136648   
6    0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.546314 -0.691870   
7    0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 -1.335162  1.517511   
8    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 -0.488498  0.412821   
9    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0 -0.206276  0.136648   
10   0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0 -1.335162  1.517511   
11   0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0 -1.335162  1.517511   
12   0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.264093 -0.415697   
13   0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.546314 -0.691870   
14   0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0 -0.018129 -0.139525   
15   1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  2.051495 -1.796561   
16   0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0 -0.958867  0.965166   
17   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.298905 -1.244215   
18   0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0 -0.488498  0.412821   
19   0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0 -0.488498  0.412821   
20   0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 -1.147015  1.241339   
21   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  2.051495 -1.796561   
22   1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 -0.958867  0.965166   
23   0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.922609 -0.968043   
24   0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 -0.958867  0.965166   
25   1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0 -0.018129 -0.139525   
26   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.264093 -0.415697   
27   1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0 -0.958867  0.965166   
28   0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.546314 -0.691870   
29   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  2.051495 -1.796561   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...       ...   
546  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.264093 -0.415697   
547  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.264093 -0.415697   
548  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 -1.335162  1.517511   
549  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.298905 -1.244215   
550  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.546314 -0.691870   
551  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  2.051495 -1.796561   
552  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.546314 -0.691870   
553  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0 -0.018129 -0.139525   
554  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.922609 -0.968043   
555  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 -0.676646  0.688993   
556  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.298905 -1.244215   
557  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 -0.676646  0.688993   
558  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0 -0.676646  0.688993   
559  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0 -0.676646  0.688993   
560  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.264093 -0.415697   
561  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 -0.676646  0.688993   
562  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0 -0.676646  0.688993   
563  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 -0.676646  0.688993   
564  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0 -0.958867  0.965166   
565  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 -0.206276  0.136648   
56

In [15]:
#define weight:

#16 for hidden layer1
#64 for hidden layer2
#64 for hidden layer3
#64 for hidden layer4
#64 for hidden layer5
#8 for output layer6

weight_hidden = np.random.random((16,64))-0.5
weight_hidden2 = np.random.random((64,64))-0.5
weight_hidden3 = np.random.random((64,64))-0.5
weight_hidden4 = np.random.random((64,64))-0.5
weight_hidden5 = np.random.random((64,8))-0.5
weight_output = np.random.random((8,1))-0.5
lr = 0.00003

bias = 0.01
bias1 = 0.01
bias2 = 0.01
bias3 = 0.01
bias4 = 0.01
bias5 = 0.01


In [16]:
def ReLU(x) :
    return x * (x > 0) + 0.01 * x * (x <= 0)

def ReLU_der(x) :
    return 1 * (x > 0) + 0.01 * (x <= 0)

def limit(x) :  
    while(np.max(x) > 0.1 or np.min(x) < -0.1) : 
            x /= 10
    return x        

In [17]:
epochtimes = 200000
mini_batch = 16
bestloss1 = 1e30 #Mini Batch Loss
preloss = 1e30   #decay the learning rate
start = time.time()

for epoch in range(epochtimes):
    X_train_random = []
    Y_train_random = []
    for i in range(mini_batch):
        rindex = random.randint(0,len(X_train)-1)
        X_train_random.append(X_train[rindex,:])
        Y_train_random.append(Y_train[rindex,:])
    X_train_random = np.array(X_train_random)
    Y_train_random = np.array(Y_train_random)
    
    
        
    input_hidden = np.dot(X_train_random, weight_hidden) + bias
    output_hidden = ReLU(input_hidden)
    
    input_hidden2 = np.dot(output_hidden, weight_hidden2) + bias1
    output_hidden2 = ReLU(input_hidden2)
    input_hidden3 = np.dot(output_hidden2, weight_hidden3) + bias2
    output_hidden3 = ReLU(input_hidden3)
    input_hidden4 = np.dot(output_hidden3, weight_hidden4) + bias3
    output_hidden4 = ReLU(input_hidden4)
    input_hidden5 = np.dot(output_hidden4, weight_hidden5) + bias4
    output_hidden5 = ReLU(input_hidden5)
    input_op = np.dot(output_hidden5, weight_output) + bias5
    output_op = ReLU(input_op)
    
    
    
    #==========================================
    
    derror_douto = output_op - Y_train_random
    douto_dino = ReLU_der(input_op)
    dino_dwo = output_hidden5      
    derror_dwo = np.dot(dino_dwo.T, derror_douto * douto_dino)
    derror_dbias5 = derror_douto * douto_dino
    
    #==========================================
    
    derror_dino = derror_douto * douto_dino
    dino_douth5 = weight_output
    derror_douth5 = np.dot(derror_dino, dino_douth5.T)
    douth5_dinh5 = ReLU_der(input_hidden5)
    dinh5_dwh5 = output_hidden4
    derror_dwh5 = np.dot(dinh5_dwh5.T, douth5_dinh5 * derror_douth5)
    derror_dbias4 = douth5_dinh5 * derror_douth5
    
    #==========================================
    
    derror_dinh5 = derror_douth5 * douth5_dinh5
    dinh5_douth4 = weight_hidden5
    derror_douth4 = np.dot(derror_dinh5, dinh5_douth4.T)
    douth4_dinh4 = ReLU_der(input_hidden4)
    dinh4_dwh4 = output_hidden3
    derror_dwh4 = np.dot(dinh4_dwh4.T, douth4_dinh4 * derror_douth4)
    derror_dbias3 = douth4_dinh4 * derror_douth4
    
    #==========================================
    
    derror_dinh4 = derror_douth4 * douth4_dinh4
    dinh4_douth3 = weight_hidden4
    derror_douth3 = np.dot(derror_dinh4, dinh4_douth3.T)
    douth3_dinh3 = ReLU_der(input_hidden3)
    dinh3_dwh3 = output_hidden2
    derror_dwh3 = np.dot(dinh3_dwh3.T, douth3_dinh3 * derror_douth3)
    derror_dbias2 = douth3_dinh3 * derror_douth3
    
    #==========================================
    
    derror_dinh3 = derror_douth3 * douth3_dinh3
    dinh3_douth2 = weight_hidden3
    derror_douth2 = np.dot(derror_dinh3, dinh3_douth2.T)
    douth2_dinh2 = ReLU_der(input_hidden2)
    dinh2_dwh2 = output_hidden
    derror_dwh2 = np.dot(dinh2_dwh2.T, douth2_dinh2 * derror_douth2)
    derror_dbias1 = douth2_dinh2 * derror_douth2
    
    #==========================================
    
    derror_dinh2 = derror_douth2 * douth2_dinh2
    dinh2_douth = weight_hidden2
    derror_douth = np.dot(derror_dinh2, dinh2_douth.T)
    douth_dinh = ReLU_der(input_hidden)
    dinh_dwh = X_train_random
    derror_dwh = np.dot(dinh_dwh.T, douth_dinh * derror_douth)
    derror_dbias = douth_dinh * derror_douth
    
    #==========================================
       
    
    
    weight_hidden -= limit(lr * derror_dwh)
    weight_hidden2 -= limit(lr * derror_dwh2)
    weight_hidden3 -= limit(lr * derror_dwh3)
    weight_hidden4 -= limit(lr * derror_dwh4)
    weight_hidden5 -= limit(lr * derror_dwh5)
    weight_output -= limit(lr * derror_dwo)
    
    bias -= lr * derror_dbias.sum()/np.size(derror_dbias)
    bias1 -= lr * derror_dbias1.sum()/np.size(derror_dbias1)
    bias2 -= lr * derror_dbias2.sum()/np.size(derror_dbias2)
    bias3 -= lr * derror_dbias3.sum()/np.size(derror_dbias3)
    bias4 -= lr * derror_dbias4.sum()/np.size(derror_dbias4)
    bias5 -= lr * derror_dbias5.sum()/np.size(derror_dbias5)
    
    error_out = ((1 / 2) * (np.power((output_op - Y_train_random), 2)))
    #print(error_out.sum())
    
        
        
    #calulate error 
    if epoch % 200 == 0 : 
        input_hidden = np.dot(X_train, weight_hidden) + bias
        output_hidden = ReLU(input_hidden)
        input_hidden2 = np.dot(output_hidden, weight_hidden2) + bias1
        output_hidden2 = ReLU(input_hidden2)
        input_hidden3 = np.dot(output_hidden2, weight_hidden3) + bias2
        output_hidden3 = ReLU(input_hidden3)
        input_hidden4 = np.dot(output_hidden3, weight_hidden4) + bias3
        output_hidden4 = ReLU(input_hidden4)
        input_hidden5 = np.dot(output_hidden4, weight_hidden5) + bias4
        output_hidden5 = ReLU(input_hidden5)
        input_op = np.dot(output_hidden5, weight_output)+ bias5
        output_op = ReLU(input_op)
        error_out = ((1 / 2) * (np.power((output_op - Y_train), 2)))
        
   
        #set decay for learning rate
        if error_out.sum() > preloss :
            lr *= 0.9
            
        preloss = error_out.sum()  
       
        
        print('now training ',epoch*100/epochtimes,'%')
        print(error_out.sum())
        #print(error_out)
        #print('\n',lr * derror_dwh,'\n', lr * derror_dwo,'\n')
        
       
        #print(derror_wh, derror_wo)



end = time.time()

now training  0.0 %
103193.95772667302
now training  0.1 %
2544.995199466343
now training  0.2 %
1753.4500625859175
now training  0.3 %
2124.881860986555
now training  0.4 %
1221.2365450677653
now training  0.5 %
1101.4452919032224
now training  0.6 %
982.6225366954757
now training  0.7 %
960.6353910670025
now training  0.8 %
819.671930244322
now training  0.9 %
733.9327462611712
now training  1.0 %
907.7393119299813
now training  1.1 %
680.4452308590255
now training  1.2 %
579.0672828987731
now training  1.3 %
561.2811082651654
now training  1.4 %
621.5304989781512
now training  1.5 %
747.2507440375309
now training  1.6 %
442.9000534599689
now training  1.7 %
402.1278183235519
now training  1.8 %
371.18785471606407
now training  1.9 %
357.35109629890815
now training  2.0 %
328.9802627134935
now training  2.1 %
301.6776220970708
now training  2.2 %
296.1049131122844
now training  2.3 %
267.54863610582976
now training  2.4 %
263.4367774375356
now training  2.5 %
239.2800767815826
now tr

now training  21.2 %
37.77997018638699
now training  21.3 %
37.70084981387823
now training  21.4 %
37.686711919133565
now training  21.5 %
37.68942101026375
now training  21.6 %
37.64774798175909
now training  21.7 %
37.637674838492394
now training  21.8 %
37.61861943692024
now training  21.9 %
37.62591848796633
now training  22.0 %
37.60099247117891
now training  22.1 %
37.61320650639297
now training  22.2 %
37.573435999204925
now training  22.3 %
37.5614342289566
now training  22.4 %
37.57565556444861
now training  22.5 %
37.53845428517461
now training  22.6 %
37.523842262303674
now training  22.7 %
37.52288362442634
now training  22.8 %
37.504257785067
now training  22.9 %
37.50345997734365
now training  23.0 %
37.503507096402025
now training  23.1 %
37.481463119924015
now training  23.2 %
37.475031908768045
now training  23.3 %
37.45749104816865
now training  23.4 %
37.464709561449205
now training  23.5 %
37.44373841414021
now training  23.6 %
37.44135767063696
now training  23.7 %

now training  42.2 %
36.88066687555917
now training  42.3 %
36.880033021260886
now training  42.4 %
36.879427184848716
now training  42.5 %
36.87891545767715
now training  42.6 %
36.87902023567915
now training  42.7 %
36.87879409917223
now training  42.8 %
36.878400588412546
now training  42.9 %
36.877387853642446
now training  43.0 %
36.877393821225375
now training  43.1 %
36.87658585144254
now training  43.2 %
36.87623074930711
now training  43.3 %
36.87579800534829
now training  43.4 %
36.8756226080027
now training  43.5 %
36.87505906694359
now training  43.6 %
36.87466615851705
now training  43.7 %
36.874440738296315
now training  43.8 %
36.873980841801085
now training  43.9 %
36.87361731405531
now training  44.0 %
36.87344998427051
now training  44.1 %
36.87354773252102
now training  44.2 %
36.87270752950155
now training  44.3 %
36.87238843508724
now training  44.4 %
36.87204896222073
now training  44.5 %
36.87183295978804
now training  44.6 %
36.87166341961348
now training  44.7 

now training  63.2 %
36.835608917242055
now training  63.3 %
36.835509206073965
now training  63.4 %
36.83542204628034
now training  63.5 %
36.835293694363486
now training  63.6 %
36.83517306734956
now training  63.7 %
36.835112566746304
now training  63.8 %
36.83500929266063
now training  63.9 %
36.83488933454946
now training  64.0 %
36.834785967595145
now training  64.1 %
36.8345997978576
now training  64.2 %
36.83445725038941
now training  64.3 %
36.834320208375075
now training  64.4 %
36.83427202135985
now training  64.5 %
36.834156708005395
now training  64.6 %
36.83397808404783
now training  64.7 %
36.833876103689406
now training  64.8 %
36.83377488344111
now training  64.9 %
36.833695671543204
now training  65.0 %
36.83354630350974
now training  65.1 %
36.8334280485702
now training  65.2 %
36.83332097782433
now training  65.3 %
36.83325710499792
now training  65.4 %
36.83312612230297
now training  65.5 %
36.832968286197016
now training  65.6 %
36.833068161645016
now training  65

now training  84.2 %
36.81890516197822
now training  84.3 %
36.818848512379404
now training  84.4 %
36.81877602369446
now training  84.5 %
36.81871673526153
now training  84.6 %
36.81864986939307
now training  84.7 %
36.818586810097784
now training  84.8 %
36.818529792569834
now training  84.9 %
36.818466920648504
now training  85.0 %
36.81842188582421
now training  85.1 %
36.81835459264524
now training  85.2 %
36.81829631067727
now training  85.3 %
36.81823585609979
now training  85.4 %
36.818173744173414
now training  85.5 %
36.81811347543386
now training  85.6 %
36.8180588215983
now training  85.7 %
36.81801336620917
now training  85.8 %
36.81793822725756
now training  85.9 %
36.81790339916218
now training  86.0 %
36.81785666151089
now training  86.1 %
36.81777577463137
now training  86.2 %
36.817726287425245
now training  86.3 %
36.817683217057194
now training  86.4 %
36.81761900142135
now training  86.5 %
36.817568110539966
now training  86.6 %
36.81753045469167
now training  86.7

In [18]:
input_hidden = np.dot(X_train, weight_hidden) 
output_hidden = ReLU(input_hidden)
input_hidden2 = np.dot(output_hidden, weight_hidden2) 
output_hidden2 = ReLU(input_hidden2)
input_hidden3 = np.dot(output_hidden2, weight_hidden3) 
output_hidden3 = ReLU(input_hidden3)
input_hidden4 = np.dot(output_hidden3, weight_hidden4) 
output_hidden4 = ReLU(input_hidden4)
input_hidden5 = np.dot(output_hidden4, weight_hidden5) 
output_hidden5 = ReLU(input_hidden5)
input_op = np.dot(output_hidden5, weight_output)
output_op = ReLU(input_op)
error_out = ((1 / len(Y_train)) * (np.power((output_op - Y_train), 2)))

print('result: ')
print(error_out.sum())

result: 
0.5261892468014845


In [19]:
single_point = np.array(X_train)
result1 = np.dot(single_point, weight_hidden) + bias
result2 = ReLU(result1)
result3 = np.dot(result2, weight_hidden2) + bias1
result4 = ReLU(result3)
result5 = np.dot(result4, weight_hidden3) + bias2
result6 = ReLU(result5)
result7 = np.dot(result6, weight_hidden4) + bias3
result8 = ReLU(result7)
result9 = np.dot(result8, weight_hidden5) + bias4
result10 = ReLU(result9)
result11 = np.dot(result10, weight_output) + bias5
result12 = ReLU(result11)
#print(result12)
#print(Y_train_random)
error_out = ((1/len(Y_train)) * (np.power((result12 - Y_train), 2)))
#print(error_out)
print(error_out.sum())

0.12781322574547568


In [20]:
print("bias:",bias )
print("bias1:",bias1 )
print("bias2:",bias2 )
print("bias3:",bias3 )
print("bias4:",bias4 )
print("bias5:",bias5 )

bias: 0.011874466199478432
bias1: 0.010540594791770608
bias2: 0.010573444772506102
bias3: 0.010302373846439374
bias4: 0.011054192332020754
bias5: 0.015475303686104756


In [21]:
single_point = np.array(X_test)
result1 = np.dot(single_point, weight_hidden)
result2 = ReLU(result1)
result3 = np.dot(result2, weight_hidden2)
result4 = ReLU(result3)
result5 = np.dot(result4, weight_hidden3)
result6 = ReLU(result5)
result7 = np.dot(result6, weight_hidden4)
result8 = ReLU(result7)
result9 = np.dot(result8, weight_hidden5)
result10 = ReLU(result9)
result11 = np.dot(result10, weight_output)
result12 = ReLU(result11)
print(result12)
print(Y_test)
print(len(X_test))
error_out = ((1/len(X_test)) * (np.power((result12 - Y_test), 2)))
print(math.sqrt(error_out.sum()))

[[17.86855886]
 [12.04122678]
 [10.27016083]
 [27.4259546 ]
 [10.90412854]
 [29.74793337]
 [14.77185587]
 [26.8833012 ]
 [33.25749216]
 [29.74324801]
 [14.06535403]
 [26.14999402]
 [26.88991871]
 [11.26670275]
 [11.95711335]
 [11.91937768]
 [10.86899828]
 [10.22110348]
 [35.10090237]
 [43.49813757]
 [34.88542955]
 [30.62328281]
 [ 9.4555839 ]
 [33.26903697]
 [12.10586484]
 [27.15654714]
 [44.68352799]
 [30.2088287 ]
 [14.36823534]
 [28.14029847]
 [32.22905106]
 [37.11882575]
 [26.43831577]
 [ 9.24621572]
 [27.80170807]
 [31.04125082]
 [31.22592754]
 [21.51641613]
 [12.05434372]
 [ 6.60039103]
 [12.4057531 ]
 [ 6.1070794 ]
 [10.83707242]
 [33.65345676]
 [14.6430867 ]
 [12.77111465]
 [13.81788552]
 [40.58457352]
 [10.27638611]
 [ 6.3632127 ]
 [11.06167591]
 [34.30863893]
 [15.76705902]
 [41.75919386]
 [13.88005954]
 [28.33837285]
 [17.87894366]
 [11.97381335]
 [38.16297177]
 [13.40201941]
 [32.33635391]
 [28.98114864]
 [33.29562984]
 [36.63124089]
 [30.75176704]
 [27.14833446]
 [12.59673

In [22]:
single_point = np.array(X_test)
result1 = np.dot(single_point, weight_hidden) + bias
result2 = ReLU(result1)
result3 = np.dot(result2, weight_hidden2) + bias1
result4 = ReLU(result3)
result5 = np.dot(result4, weight_hidden3) + bias2
result6 = ReLU(result5)
result7 = np.dot(result6, weight_hidden4) + bias3
result8 = ReLU(result7)
result9 = np.dot(result8, weight_hidden5) + bias4
result10 = ReLU(result9)
result11 = np.dot(result10, weight_output) + bias5
result12 = ReLU(result11)
print(result12)
print(Y_test)
print(len(X_test))
error_out = ((1/len(X_test)) * (np.power((result12 - Y_test), 2)))
print(math.sqrt(error_out.sum()))

[[18.29370952]
 [12.42157747]
 [10.47053902]
 [28.32483948]
 [11.23053479]
 [30.48405969]
 [15.29707803]
 [27.77343544]
 [34.38273609]
 [30.4270158 ]
 [14.46208173]
 [26.8381822 ]
 [27.44383178]
 [11.73961057]
 [12.42240677]
 [12.35582452]
 [11.27006502]
 [10.6770136 ]
 [35.65338456]
 [44.29178453]
 [35.7589598 ]
 [31.53072204]
 [ 9.82206574]
 [34.29449662]
 [12.55288161]
 [27.98080853]
 [45.18493997]
 [30.95872799]
 [14.67041444]
 [28.8795798 ]
 [33.07129695]
 [38.18073561]
 [27.2324746 ]
 [ 9.65583372]
 [28.51230255]
 [32.06040529]
 [31.83463548]
 [21.90047566]
 [12.48089308]
 [ 6.90631169]
 [12.73909458]
 [ 6.37729904]
 [11.21088615]
 [34.58506063]
 [15.128515  ]
 [13.13895374]
 [14.27572188]
 [41.41434809]
 [10.70578357]
 [ 6.72550153]
 [11.47294345]
 [34.83601722]
 [16.25246125]
 [42.56891976]
 [14.36542133]
 [28.89318408]
 [18.29424781]
 [12.42219407]
 [39.1445817 ]
 [13.93509802]
 [32.98774013]
 [29.81339478]
 [34.11292013]
 [37.75375492]
 [31.62096392]
 [27.88206141]
 [12.99673