In [1]:
import numpy as np
import math
import pandas 
import random 
import time
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn import preprocessing

In [2]:
dataframe = pandas.read_csv("ENB2012_data.csv")

dataframe.columns = ['relative_compactness', 'surface_area', 
                     'wall_area', 'roof_area', 'overall_height', 
                     'orientation', 'glazing_area', 
                     'glazing_area_distribution', 'heating_load', 
                     'cooling_load']

In [3]:
print(dataframe.head())

   relative_compactness  surface_area  wall_area  roof_area  overall_height  \
0                  0.98         514.5      294.0     110.25             7.0   
1                  0.98         514.5      294.0     110.25             7.0   
2                  0.98         514.5      294.0     110.25             7.0   
3                  0.98         514.5      294.0     110.25             7.0   
4                  0.90         563.5      318.5     122.50             7.0   

   orientation  glazing_area  glazing_area_distribution  heating_load  \
0            2           0.0                          0         15.55   
1            3           0.0                          0         15.55   
2            4           0.0                          0         15.55   
3            5           0.0                          0         15.55   
4            2           0.0                          0         20.84   

   cooling_load  
0         21.33  
1         21.33  
2         21.33  
3         21.3

In [4]:
print(dataframe.describe())

       relative_compactness  surface_area   wall_area   roof_area  \
count            768.000000    768.000000  768.000000  768.000000   
mean               0.764167    671.708333  318.500000  176.604167   
std                0.105777     88.086116   43.626481   45.165950   
min                0.620000    514.500000  245.000000  110.250000   
25%                0.682500    606.375000  294.000000  140.875000   
50%                0.750000    673.750000  318.500000  183.750000   
75%                0.830000    741.125000  343.000000  220.500000   
max                0.980000    808.500000  416.500000  220.500000   

       overall_height  orientation  glazing_area  glazing_area_distribution  \
count       768.00000   768.000000    768.000000                  768.00000   
mean          5.25000     3.500000      0.234375                    2.81250   
std           1.75114     1.118763      0.133221                    1.55096   
min           3.50000     2.000000      0.000000              

In [5]:
print("Shape:", dataframe.shape)

Shape: (768, 10)


In [6]:
print("Data Types:", dataframe.dtypes)

Data Types: relative_compactness         float64
surface_area                 float64
wall_area                    float64
roof_area                    float64
overall_height               float64
orientation                    int64
glazing_area                 float64
glazing_area_distribution      int64
heating_load                 float64
cooling_load                 float64
dtype: object


In [7]:
print("Correlation:", dataframe.corr(method='pearson'))

Correlation:                            relative_compactness  surface_area     wall_area  \
relative_compactness               1.000000e+00 -9.919015e-01 -2.037817e-01   
surface_area                      -9.919015e-01  1.000000e+00  1.955016e-01   
wall_area                         -2.037817e-01  1.955016e-01  1.000000e+00   
roof_area                         -8.688234e-01  8.807195e-01 -2.923165e-01   
overall_height                     8.277473e-01 -8.581477e-01  2.809757e-01   
orientation                        0.000000e+00  0.000000e+00  0.000000e+00   
glazing_area                       1.283986e-17  1.318356e-16 -7.969726e-19   
glazing_area_distribution          1.764620e-17 -3.558613e-16  0.000000e+00   
heating_load                       6.222722e-01 -6.581202e-01  4.556712e-01   
cooling_load                       6.343391e-01 -6.729989e-01  4.271170e-01   

                              roof_area  overall_height  orientation  \
relative_compactness      -8.688234e-01    8.

In [8]:
print(dataframe.values)

[[9.800e-01 5.145e+02 2.940e+02 ... 0.000e+00 1.555e+01 2.133e+01]
 [9.800e-01 5.145e+02 2.940e+02 ... 0.000e+00 1.555e+01 2.133e+01]
 [9.800e-01 5.145e+02 2.940e+02 ... 0.000e+00 1.555e+01 2.133e+01]
 ...
 [6.200e-01 8.085e+02 3.675e+02 ... 5.000e+00 1.644e+01 1.711e+01]
 [6.200e-01 8.085e+02 3.675e+02 ... 5.000e+00 1.648e+01 1.661e+01]
 [6.200e-01 8.085e+02 3.675e+02 ... 5.000e+00 1.664e+01 1.603e+01]]


In [9]:
dataset = np.array(dataframe.values)
dataset_shuf = []
index_shuf = list(range(len(dataset)))
random.shuffle(index_shuf)
for i in index_shuf:
    dataset_shuf.append(dataset[i,:])   
dataset_shuf = np.array(dataset_shuf)
dataset_shuf.reshape(768,10)

array([[9.000e-01, 5.635e+02, 3.185e+02, ..., 2.000e+00, 3.327e+01,
        3.264e+01],
       [7.900e-01, 6.370e+02, 3.430e+02, ..., 4.000e+00, 3.545e+01,
        4.186e+01],
       [9.000e-01, 5.635e+02, 3.185e+02, ..., 4.000e+00, 3.328e+01,
        3.316e+01],
       ...,
       [6.900e-01, 7.350e+02, 2.940e+02, ..., 2.000e+00, 1.475e+01,
        1.644e+01],
       [8.600e-01, 5.880e+02, 2.940e+02, ..., 0.000e+00, 1.934e+01,
        2.349e+01],
       [9.800e-01, 5.145e+02, 2.940e+02, ..., 5.000e+00, 3.272e+01,
        3.323e+01]])

In [10]:
X_train = dataset_shuf[:576,0:8]
Y_train = dataset_shuf[:576,8:9]
X_train.reshape(576,8)
Y_train.reshape(576,1)

X_test = dataset_shuf[576:,0:8]
Y_test = dataset_shuf[576:,8:9]
X_test.reshape(192,8)
Y_test.reshape(192,1)

array([[32.21],
       [35.99],
       [32.67],
       [25.43],
       [14.08],
       [13.02],
       [19.06],
       [14.58],
       [29.79],
       [14.41],
       [37.24],
       [31.29],
       [28.56],
       [28.15],
       [24.6 ],
       [12.47],
       [32.26],
       [12.41],
       [23.84],
       [12.87],
       [28.67],
       [25.7 ],
       [26.84],
       [12.43],
       [35.73],
       [11.42],
       [32.31],
       [33.27],
       [24.4 ],
       [32.06],
       [16.44],
       [11.43],
       [41.3 ],
       [12.29],
       [15.23],
       [16.44],
       [32.94],
       [16.76],
       [36.06],
       [24.96],
       [11.16],
       [14.54],
       [25.37],
       [36.47],
       [15.55],
       [36.7 ],
       [12.86],
       [39.86],
       [28.17],
       [28.95],
       [11.18],
       [10.77],
       [16.86],
       [35.48],
       [28.61],
       [15.36],
       [15.41],
       [28.63],
       [29.67],
       [16.66],
       [32.73],
       [15.16],
       [

In [11]:
transformer = ColumnTransformer([('one_hot_encoder', OneHotEncoder(), [5,7])],remainder='passthrough')
X_train = np.array(transformer.fit_transform(X_train), dtype=np.float)

X_test = np.array(transformer.fit_transform(X_test), dtype=np.float)



In [12]:
pandas.DataFrame(X_train)

0    1    2    3    4    5    6    7    8    9    10     11     12  \
0    0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.90  563.5  318.5   
1    0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.79  637.0  343.0   
2    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.90  563.5  318.5   
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.82  612.5  318.5   
4    0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.69  735.0  294.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...    ...    ...   
571  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.74  686.0  245.0   
572  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.69  735.0  294.0   
573  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.71  710.5  269.5   
574  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.71  710.5  269.5   
575  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.64  784.0  343.0   

        13   14    15  
0    122.5  7.0  0.25  
1    147.0  7.0  0.10  
2    122.5  7.0  0.25  
3    147.0  7.0  0.40  
4    220.5  3.5  0.25  
..     ...  ...   ...  
571  220.5  3.5  0.25  
572  220.5  3.5  0.40  
573  220.5  3.5  0.00  
574  220.5  3.5  0.40  
575  220.5  3.5  0.25  

[576 rows x 16 columns]

In [13]:
X_scaled = np.copy(X_train[:,10:16])
X_scaled2 = np.copy(X_test[:,10:16])

scaler = preprocessing.StandardScaler().fit(X_scaled)

X_scaled = scaler.transform(X_scaled)
X_scaled2 = scaler.transform(X_scaled2)


In [14]:
X_train = np.copy(X_train[:,0:10])
X_test = np.copy(X_test[:,0:10])
X_train = np.append(X_train, X_scaled, axis = 1)
X_test = np.append(X_test, X_scaled2, axis = 1)

pandas.DataFrame(X_train)

0    1    2    3    4    5    6    7    8    9        10        11  \
0    0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.317978 -1.255403   
1    0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.273094 -0.422005   
2    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.317978 -1.255403   
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.558063 -0.699804   
4    0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0 -0.676799  0.689194   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...       ...   
571  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0 -0.201852  0.133595   
572  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 -0.676799  0.689194   
573  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0 -0.486821  0.411394   
574  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 -0.486821  0.411394   
575  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 -1.151746  1.244793   

           12        13        14        15  
0   -0.011626 -1.224903  1.021055  0.126122  
1    0.546401 -0.680291  1.021055 -1.014916  
2   -0.011626 -1.224903  1.021055  0.126122  
3   -0.011626 -0.680291  1.021055  1.267160  
4   -0.569652  0.953543 -0.979379  0.126122  
..        ...       ...       ...       ...  
571 -1.685705  0.953543 -0.979379  0.126122  
572 -0.569652  0.953543 -0.979379  1.267160  
573 -1.127678  0.953543 -0.979379 -1.775608  
574 -1.127678  0.953543 -0.979379  1.267160  
575  0.546401  0.953543 -0.979379  0.126122  

[576 rows x 16 columns]

In [15]:
#define weight:

#7 for hidden layer1
#5 for hidden layer2
#2 for output layer
#9 total

weight_hidden = np.random.random((16,64))-0.5
weight_hidden2 = np.random.random((64,64))-0.5
weight_hidden3 = np.random.random((64,64))-0.5
weight_hidden4 = np.random.random((64,64))-0.5
weight_hidden5 = np.random.random((64,8))-0.5
weight_output = np.random.random((8,1))-0.5
lr = 0.00001
bias = 0.3


In [16]:
def ReLU(x) :
    return x * (x > 0) + 0.01 * x * (x <= 0)

def ReLU_der(x) :
    return 1 * (x > 0) + 0.01 * (x <= 0)

def limit(x) :  
    while(np.max(x) > 0.1 or np.min(x) < -0.1) : 
            x /= 10
    return x        

In [29]:
epochtimes = 200000
mini_batch = 128
bestloss1 = 1e30 #Mini Batch Loss
preloss = 1e30   #decay the learning rate
start = time.time()

for epoch in range(epochtimes):
    X_train_random = []
    Y_train_random = []
    for i in range(mini_batch):
        rindex = random.randint(0,len(X_train)-1)
        X_train_random.append(X_train[rindex,:])
        Y_train_random.append(Y_train[rindex,:])
    X_train_random = np.array(X_train_random)
    Y_train_random = np.array(Y_train_random)
    
        
    input_hidden = np.dot(X_train_random, weight_hidden) 
    output_hidden = ReLU(input_hidden)
    
    input_hidden2 = np.dot(output_hidden, weight_hidden2) 
    output_hidden2 = ReLU(input_hidden2)
    input_hidden3 = np.dot(output_hidden2, weight_hidden3) 
    output_hidden3 = ReLU(input_hidden3)
    input_hidden4 = np.dot(output_hidden3, weight_hidden4) 
    output_hidden4 = ReLU(input_hidden4)
    input_hidden5 = np.dot(output_hidden4, weight_hidden5) 
    output_hidden5 = ReLU(input_hidden5)
    input_op = np.dot(output_hidden5, weight_output)
    output_op = ReLU(input_op)
    
    
    
    #==========================================
    
    derror_douto = output_op - Y_train_random
    douto_dino = ReLU_der(input_op)
    dino_dwo = output_hidden5      
    derror_dwo = np.dot(dino_dwo.T, derror_douto * douto_dino)
    
    #==========================================
    
    derror_dino = derror_douto * douto_dino
    dino_douth5 = weight_output
    derror_douth5 = np.dot(derror_dino, dino_douth5.T)
    douth5_dinh5 = ReLU_der(input_hidden5)
    dinh5_dwh5 = output_hidden4
    derror_dwh5 = np.dot(dinh5_dwh5.T, douth5_dinh5 * derror_douth5)
    
    #==========================================
    
    derror_dinh5 = derror_douth5 * douth5_dinh5
    dinh5_douth4 = weight_hidden5
    derror_douth4 = np.dot(derror_dinh5, dinh5_douth4.T)
    douth4_dinh4 = ReLU_der(input_hidden4)
    dinh4_dwh4 = output_hidden3
    derror_dwh4 = np.dot(dinh4_dwh4.T, douth4_dinh4 * derror_douth4)
    
    #==========================================
    
    derror_dinh4 = derror_douth4 * douth4_dinh4
    dinh4_douth3 = weight_hidden4
    derror_douth3 = np.dot(derror_dinh4, dinh4_douth3.T)
    douth3_dinh3 = ReLU_der(input_hidden3)
    dinh3_dwh3 = output_hidden2
    derror_dwh3 = np.dot(dinh3_dwh3.T, douth3_dinh3 * derror_douth3)
    
    #==========================================
    
    derror_dinh3 = derror_douth3 * douth3_dinh3
    dinh3_douth2 = weight_hidden3
    derror_douth2 = np.dot(derror_dinh3, dinh3_douth2.T)
    douth2_dinh2 = ReLU_der(input_hidden2)
    dinh2_dwh2 = output_hidden
    derror_dwh2 = np.dot(dinh2_dwh2.T, douth2_dinh2 * derror_douth2)
    
    #==========================================
    
    derror_dinh2 = derror_douth2 * douth2_dinh2
    dinh2_douth = weight_hidden2
    derror_douth = np.dot(derror_dinh2, dinh2_douth.T)
    douth_dinh = ReLU_der(input_hidden)
    dinh_dwh = X_train_random
    derror_dwh = np.dot(dinh_dwh.T, douth_dinh * derror_douth)
    
    #==========================================
       
    
    
    weight_hidden -= limit(lr * derror_dwh)
    weight_hidden2 -= limit(lr * derror_dwh2)
    weight_hidden3 -= limit(lr * derror_dwh3)
    weight_hidden4 -= limit(lr * derror_dwh4)
    weight_hidden5 -= limit(lr * derror_dwh5)
    weight_output -= limit(lr * derror_dwo)
    
    
    error_out = ((1 / 2) * (np.power((output_op - Y_train_random), 2)))
    #print(error_out.sum())
    
        
        
    #calulate error 
    if epoch % 200 == 0 : 
        input_hidden = np.dot(X_train, weight_hidden) 
        output_hidden = ReLU(input_hidden)
        input_hidden2 = np.dot(input_hidden, weight_hidden2) 
        output_hidden2 = ReLU(input_hidden2)
        input_hidden3 = np.dot(output_hidden2, weight_hidden3) 
        output_hidden3 = ReLU(input_hidden3)
        input_hidden4 = np.dot(output_hidden3, weight_hidden4) 
        output_hidden4 = ReLU(input_hidden4)
        input_hidden5 = np.dot(output_hidden4, weight_hidden5) 
        output_hidden5 = ReLU(input_hidden5)
        input_op = np.dot(output_hidden5, weight_output)
        output_op = ReLU(input_op)
        error_out = ((1 / 2) * (np.power((output_op - Y_train), 2)))
        
        if epoch == 0 : 
            preloss = error_out.sum()     
            
        if error_out.sum() < preloss :
            mbwh1 = np.copy(weight_hidden)     #collect the best minibatch weight vector
            mbwh2 = np.copy(weight_hidden2)
            mbwh3 = np.copy(weight_hidden3)
            mbwh4 = np.copy(weight_hidden4)
            mbwh5 = np.copy(weight_hidden5)
            mbwo  = np.copy(weight_output)
            lr *= error_out.sum() / preloss
            preloss = error_out.sum()  
        
        print('now training ',epoch*100/epochtimes,'%')
        print(error_out.sum())
        #print(error_out)
        #print('\n',lr * derror_dwh,'\n', lr * derror_dwo,'\n')
        
       
    #print(derror_wh, derror_wo)
end = time.time()

now training  0.0 %
54914.88055032281
now training  0.1 %
54866.23993532467
now training  0.2 %
54942.731379637655
now training  0.3 %
54890.87300627182
now training  0.4 %
54894.41917655515
now training  0.5 %
54880.80490654864
now training  0.6 %
54928.02011536254
now training  0.7 %
54922.832906969066
now training  0.8 %
54916.853358056695
now training  0.9 %
54859.28870567559
now training  1.0 %
54876.75482761553
now training  1.1 %
54928.97544038393
now training  1.2 %
54947.913163416335
now training  1.3 %
54964.93870757283
now training  1.4 %
54953.91605897802
now training  1.5 %
54948.0262399239
now training  1.6 %
54978.36518269286
now training  1.7 %
54971.23158580596
now training  1.8 %
54922.78150602102
now training  1.9 %
54914.22403662032
now training  2.0 %
54939.15462107598
now training  2.1 %
54981.63244573098
now training  2.2 %
54917.40026300587
now training  2.3 %
54876.38962103727
now training  2.4 %
54966.89698355668
now training  2.5 %
54969.24871680123
now train

now training  21.2 %
55460.44817600155
now training  21.3 %
55438.23535857542
now training  21.4 %
55450.68725063418
now training  21.5 %
55456.031452165465
now training  21.6 %
55438.92908761816
now training  21.7 %
55432.46058639086
now training  21.8 %
55468.0109777083
now training  21.9 %
55425.670048739375
now training  22.0 %
55425.48917606672
now training  22.1 %
55470.70417607791
now training  22.2 %
55482.86913301346
now training  22.3 %
55467.18045676834
now training  22.4 %
55455.95378879049
now training  22.5 %
55450.49922050114
now training  22.6 %
55463.80499780591
now training  22.7 %
55464.620671170094
now training  22.8 %
55463.9213087615
now training  22.9 %
55460.787014750254
now training  23.0 %
55476.37879103748
now training  23.1 %
55486.37718398281
now training  23.2 %
55510.87713300921
now training  23.3 %
55490.239049183736
now training  23.4 %
55489.44180791537
now training  23.5 %
55479.28530573822
now training  23.6 %
55501.10361304809
now training  23.7 %
5

now training  42.2 %
55575.03695604788
now training  42.3 %
55579.4745172816
now training  42.4 %
55570.27855976
now training  42.5 %
55576.32972913373
now training  42.6 %
55583.17062236275
now training  42.7 %
55569.71098263489
now training  42.8 %
55576.4710833966
now training  42.9 %
55567.66173912388
now training  43.0 %
55574.65375636946
now training  43.1 %
55578.02502079079
now training  43.2 %
55568.47612988869
now training  43.3 %
55582.999360482805
now training  43.4 %
55585.41113114052
now training  43.5 %
55573.00876908104
now training  43.6 %
55584.82880507475
now training  43.7 %
55572.57498105247
now training  43.8 %
55584.36117697015
now training  43.9 %
55567.272414993975
now training  44.0 %
55575.322986500556
now training  44.1 %
55581.47549476896
now training  44.2 %
55568.32233548998
now training  44.3 %
55573.21110817991
now training  44.4 %
55576.45703572704
now training  44.5 %
55573.66480491383
now training  44.6 %
55577.19067464295
now training  44.7 %
55579.

now training  63.1 %
55522.15885430599
now training  63.2 %
55519.88649358312
now training  63.3 %
55519.60961655964
now training  63.4 %
55522.93792569027
now training  63.5 %
55521.859493457305
now training  63.6 %
55518.814055039766
now training  63.7 %
55518.075654490865
now training  63.8 %
55520.555386931526
now training  63.9 %
55514.000671716705
now training  64.0 %
55511.02776421094
now training  64.1 %
55513.49721462704
now training  64.2 %
55516.872062898445
now training  64.3 %
55514.54354807969
now training  64.4 %
55519.0914333487
now training  64.5 %
55514.55607798971
now training  64.6 %
55517.989349810334
now training  64.7 %
55506.330475667535
now training  64.8 %
55511.92547681919
now training  64.9 %
55518.65407631216
now training  65.0 %
55516.99378144296
now training  65.1 %
55515.65224957559
now training  65.2 %
55517.97673726671
now training  65.3 %
55515.77470579584
now training  65.4 %
55516.62229286632
now training  65.5 %
55512.16713045443
now training  65.6

now training  84.0 %
55444.22482079164
now training  84.1 %
55445.70343590676
now training  84.2 %
55447.217081274386
now training  84.3 %
55445.955142719904
now training  84.4 %
55445.892547653726
now training  84.5 %
55446.40782095148
now training  84.6 %
55446.06735944912
now training  84.7 %
55446.27436437836
now training  84.8 %
55445.90536710818
now training  84.9 %
55444.83329388467
now training  85.0 %
55441.6097582246
now training  85.1 %
55442.71960787567
now training  85.2 %
55445.23959552971
now training  85.3 %
55442.27443956127
now training  85.4 %
55442.47034562244
now training  85.5 %
55443.0072019919
now training  85.6 %
55442.81872601565
now training  85.7 %
55441.428546941475
now training  85.8 %
55441.08192684305
now training  85.9 %
55443.55671884189
now training  86.0 %
55440.452022497986
now training  86.1 %
55442.1075357147
now training  86.2 %
55442.22392081153
now training  86.3 %
55440.39781572447
now training  86.4 %
55439.51511002265
now training  86.5 %
55

In [18]:
#print(weight_hidden)
print(lr * derror_dwh)
print(lr * derror_dwh2)
print(lr * derror_dwh3)
print(lr * derror_dwh4)
print(lr * derror_dwh5)
print(lr * derror_dwo)
print("Elapsed (with compilation) = %s" % (end - start))

[[ 1.86911682e-06  6.43288850e-07  4.15102538e-07 ...  8.71373892e-07
  -5.96282256e-07  9.79096224e-08]
 [ 1.28232005e-06  7.25169479e-07  1.77898205e-07 ... -3.52333347e-09
  -3.29764985e-07  1.74583502e-09]
 [ 7.16353394e-07 -1.21247187e-06 -2.77419759e-07 ...  9.48543113e-07
  -2.05538823e-06 -1.08951977e-09]
 ...
 [-2.54493315e-06 -9.11280595e-07  8.35945419e-07 ... -6.85888336e-07
   4.10643961e-06 -1.09636679e-07]
 [ 1.73339669e-06  7.47552492e-07 -7.96398760e-07 ...  7.71127251e-07
  -3.57154713e-06  8.95189814e-08]
 [ 4.46604974e-06  1.99081801e-06  6.79185249e-07 ...  4.32474899e-07
  -3.44846243e-06 -8.66141711e-08]]
[[ 5.64294133e-07  1.23721804e-06 -2.32000255e-09 ...  3.64772943e-07
  -1.97543867e-06  9.05378217e-07]
 [ 2.84306740e-08 -1.75539672e-07 -5.46669633e-10 ... -1.00901222e-07
   3.69011068e-07 -8.02408483e-07]
 [ 1.05697175e-07  1.78116371e-07  8.56563918e-11 ... -3.65930529e-08
  -2.68824068e-07  3.44644425e-07]
 ...
 [ 1.95356691e-07 -7.97407459e-08  3.7870933

In [30]:
single_point = np.array(X_train)
result1 = np.dot(single_point, weight_hidden)
result2 = ReLU(result1)
result3 = np.dot(result2, weight_hidden2)
result4 = ReLU(result3)
result5 = np.dot(result4, weight_hidden3)
result6 = ReLU(result5)
result7 = np.dot(result6, weight_hidden4)
result8 = ReLU(result7)
result9 = np.dot(result8, weight_hidden5)
result10 = ReLU(result9)
result11 = np.dot(result10, weight_output)
result12 = ReLU(result11)
#print(result12)
#print(Y_train_random)
error_out = ((1/len(Y_train)) * (np.power((result12 - Y_train), 2)))
#print(error_out)
print(error_out.sum())

1.0218172973052488e-05


In [32]:
single_point = np.array(X_test)
result1 = np.dot(single_point, weight_hidden)
result2 = ReLU(result1)
result3 = np.dot(result2, weight_hidden2)
result4 = ReLU(result3)
result5 = np.dot(result4, weight_hidden3)
result6 = ReLU(result5)
result7 = np.dot(result6, weight_hidden4)
result8 = ReLU(result7)
result9 = np.dot(result8, weight_hidden5)
result10 = ReLU(result9)
result11 = np.dot(result10, weight_output)
result12 = ReLU(result11)
print(result12)
print(Y_test)
print(len(X_test))
error_out = ((1/len(X_test)) * (np.power((result12 - Y_test), 2)))
print(math.sqrt(error_out.sum()))

[[32.13019721]
 [36.98304639]
 [32.13389434]
 [27.11138245]
 [13.72066162]
 [16.56793144]
 [21.03726633]
 [15.46069275]
 [29.06649501]
 [11.36826686]
 [34.1042784 ]
 [29.31932746]
 [29.73784315]
 [27.60910403]
 [29.44723199]
 [13.32020899]
 [34.01244006]
 [14.84013686]
 [26.02907149]
 [14.46334995]
 [27.83565056]
 [30.1848088 ]
 [28.71482709]
 [10.22741394]
 [34.94870274]
 [12.87040886]
 [32.93389551]
 [34.81344884]
 [26.69211823]
 [31.07394477]
 [14.79589129]
 [13.23779766]
 [41.85806882]
 [13.53684666]
 [17.41482654]
 [18.67257255]
 [33.06230753]
 [15.43576651]
 [34.27375567]
 [27.66225949]
 [12.03651016]
 [15.00169167]
 [29.38885784]
 [34.69649096]
 [17.36495127]
 [33.67687821]
 [14.02345117]
 [42.31797633]
 [29.24246357]
 [31.2552352 ]
 [10.04788538]
 [10.13612086]
 [15.7006402 ]
 [34.557012  ]
 [30.24445234]
 [16.91657383]
 [13.90193115]
 [31.9811879 ]
 [33.40290996]
 [15.68817071]
 [36.84955473]
 [13.60340612]
 [43.07260931]
 [42.67994558]
 [17.55177462]
 [17.29614331]
 [27.31181

In [21]:
single_point = np.array(X_train)
result1 = np.dot(single_point, mbwh1)
result2 = ReLU(result1)
result3 = np.dot(result2, mbwh2)
result4 = ReLU(result3)
result5 = np.dot(result4, mbwh3)
result6 = ReLU(result5)
result7 = np.dot(result6, mbwh4)
result8 = ReLU(result7)
result9 = np.dot(result8, mbwh5)
result10 = ReLU(result9)
result11 = np.dot(result10, mbwo)
result12 = ReLU(result11)
print("bestloss1 = ", bestloss1)
#print(result12)
#print(Y_train_random)
error_out = ((1/len(Y_train)) * (np.power((result12 - Y_train), 2)))
print(error_out.sum())

bestloss1 =  1e+30
6.730482153168909
