In [1]:
import numpy as np
import math
import pandas 
import random 
import time
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn import preprocessing

In [2]:
dataframe = pandas.read_csv("ionosphere_data.csv")

In [3]:
print(dataframe.head())

   1  0  0.99539  -0.05889  0.85243  0.02306  0.83398  -0.37708      1.1  \
0  1  0  1.00000  -0.18829  0.93035 -0.36156 -0.10868  -0.93597  1.00000   
1  1  0  1.00000  -0.03365  1.00000  0.00485  1.00000  -0.12062  0.88965   
2  1  0  1.00000  -0.45161  1.00000  1.00000  0.71216  -1.00000  0.00000   
3  1  0  1.00000  -0.02401  0.94140  0.06531  0.92106  -0.23255  0.77152   
4  1  0  0.02337  -0.00592 -0.09924 -0.11949 -0.00763  -0.11824  0.14706   

   0.03760  ...  -0.51171  0.41078  -0.46168  0.21266  -0.34090  0.42267  \
0 -0.04549  ...  -0.26569 -0.20468  -0.18401 -0.19040  -0.11593 -0.16626   
1  0.01198  ...  -0.40220  0.58984  -0.22145  0.43100  -0.17365  0.60436   
2  0.00000  ...   0.90695  0.51613   1.00000  1.00000  -0.20099  0.25682   
3 -0.16399  ...  -0.65158  0.13290  -0.53206  0.02431  -0.62197 -0.05707   
4  0.06637  ...  -0.01535 -0.03240   0.09223 -0.07859   0.00732  0.00000   

   -0.54487  0.18641  -0.45300  g  
0  -0.06288 -0.13738  -0.02447  b  
1  -0.24180  0

In [4]:
print(dataframe.describe())

                1      0     0.99539    -0.05889     0.85243     0.02306  \
count  350.000000  350.0  350.000000  350.000000  350.000000  350.000000   
mean     0.891429    0.0    0.640330    0.044667    0.600350    0.116154   
std      0.311546    0.0    0.498059    0.442032    0.520431    0.461443   
min      0.000000    0.0   -1.000000   -1.000000   -1.000000   -1.000000   
25%      1.000000    0.0    0.471518   -0.065388    0.412555   -0.024868   
50%      1.000000    0.0    0.870795    0.016700    0.808620    0.021170   
75%      1.000000    0.0    1.000000    0.194727    1.000000    0.335318   
max      1.000000    0.0    1.000000    1.000000    1.000000    1.000000   

          0.83398    -0.37708         1.1     0.03760  ...     0.56811  \
count  350.000000  350.000000  350.000000  350.000000  ...  350.000000   
mean     0.549284    0.120779    0.510453    0.181756  ...    0.395643   
std      0.493124    0.520816    0.507117    0.484482  ...    0.579206   
min     -1.000000  

In [5]:
print("Shape:", dataframe.shape)

Shape: (350, 35)


In [6]:
print("Data Types:", dataframe.dtypes)

Data Types: 1              int64
0              int64
0.99539      float64
-0.05889     float64
0.85243      float64
0.02306      float64
0.83398      float64
-0.37708     float64
1.1          float64
0.03760      float64
0.85243.1    float64
-0.17755     float64
0.59755      float64
-0.44945     float64
0.60536      float64
-0.38223     float64
0.84356      float64
-0.38542     float64
0.58212      float64
-0.32192     float64
0.56971      float64
-0.29674     float64
0.36946      float64
-0.47357     float64
0.56811      float64
-0.51171     float64
0.41078      float64
-0.46168     float64
0.21266      float64
-0.34090     float64
0.42267      float64
-0.54487     float64
0.18641      float64
-0.45300     float64
g             object
dtype: object


In [7]:
print(dataframe.values)

[[1 0 1.0 ... -0.13738 -0.02447 'b']
 [1 0 1.0 ... 0.56045 -0.38238 'g']
 [1 0 1.0 ... -0.32382 1.0 'b']
 ...
 [1 0 0.94701 ... 0.9269700000000001 -0.00577 'g']
 [1 0 0.9060799999999999 ... 0.87403 -0.16243 'g']
 [1 0 0.8471 ... 0.85764 -0.06151 'g']]


In [8]:
dataset = np.array(dataframe.values)
dataset_shuf = []
index_shuf = list(range(len(dataset)))
random.shuffle(index_shuf)
for i in index_shuf:
    dataset_shuf.append(dataset[i,:])   
dataset_shuf = np.array(dataset_shuf)
dataset_shuf.reshape(350,35)

array([[1, 0, 1.0, ..., 0.29220999999999997, -0.8962100000000001, 'g'],
       [0, 0, 1.0, ..., 1.0, -1.0, 'b'],
       [1, 0, 0.8225399999999999, ..., 0.7843899999999999, 0.01214, 'g'],
       ...,
       [1, 0, 0.19466, ..., -0.30153, -0.33588, 'g'],
       [1, 0, 1.0, ..., 1.0, 1.0, 'b'],
       [0, 0, 1.0, ..., 0.0, 0.0, 'b']], dtype=object)

In [9]:
X_train = np.array(dataset_shuf[:280,0:34], dtype = np.float)
Y_train = np.array(dataset_shuf[:280,34:35], dtype = np.object)
X_train.reshape(280,34)
Y_train.reshape(280,1)

X_test = np.array(dataset_shuf[280:,0:34], dtype = np.float)
Y_test = np.array(dataset_shuf[280:,34:35], dtype = np.object)
X_test.reshape(70,34)
Y_test.reshape(70,1)

array([['g'],
       ['g'],
       ['g'],
       ['g'],
       ['b'],
       ['g'],
       ['b'],
       ['b'],
       ['g'],
       ['g'],
       ['b'],
       ['b'],
       ['g'],
       ['b'],
       ['g'],
       ['g'],
       ['g'],
       ['g'],
       ['g'],
       ['b'],
       ['g'],
       ['b'],
       ['g'],
       ['b'],
       ['g'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['g'],
       ['g'],
       ['g'],
       ['g'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['g'],
       ['g'],
       ['g'],
       ['g'],
       ['g'],
       ['g'],
       ['g'],
       ['b'],
       ['g'],
       ['g'],
       ['g'],
       ['g'],
       ['g'],
       ['g'],
       ['g'],
       ['b'],
       ['b'],
       ['b'],
       ['g'],
       ['b'],
       ['g'],
       ['b'],
       ['b'],
       ['g'],
       ['b'],
       ['g'],
       ['g'],
       ['g'],
       ['g'],
       ['b'],
       ['b']], dtype=object)

In [10]:
labelencoder = LabelEncoder()

Y_train[:,0] = labelencoder.fit_transform(Y_train[:, 0])
Y_test[:,0] = labelencoder.fit_transform(Y_test[:, 0])





In [11]:
pandas.DataFrame(X_train)
X_train

array([[ 1.     ,  0.     ,  1.     , ..., -0.88846,  0.29221, -0.89621],
       [ 0.     ,  0.     ,  1.     , ...,  1.     ,  1.     , -1.     ],
       [ 1.     ,  0.     ,  0.82254, ..., -0.0422 ,  0.78439,  0.01214],
       ...,
       [ 1.     ,  0.     ,  0.28409, ..., -0.70076,  0.     ,  0.     ],
       [ 1.     ,  0.     ,  0.39394, ...,  0.0641 ,  0.39394,  0.24242],
       [ 1.     ,  0.     ,  0.97714, ..., -0.33662, -0.59943, -0.497  ]])

In [12]:
#define weight:

#7 for hidden layer1
#5 for hidden layer2
#2 for output layer
#9 total

weight_hidden = np.random.random((34,68))-0.5
weight_hidden2 = np.random.random((68,34))-0.5
weight_hidden3 = np.random.random((34,34))-0.5
weight_hidden4 = np.random.random((34,34))-0.5
weight_hidden5 = np.random.random((34,2))-0.5
weight_output = np.random.random((2,1))-0.5
lr = 0.003
bias = 0.3


In [13]:
def ReLU(x) :
    return x * (x > 0) + 0.01 * x * (x <= 0)

def ReLU_der(x) :
    return 1 * (x > 0) + 0.01 * (x <= 0)

def Sigmoid(x) :
    return 1/(1+np.exp(-x))

def Sigmoid_der(x) :
    return Sigmoid(x) * (1 - Sigmoid(x))

def limit(x) :  
    while(np.max(x) > 0.1 or np.min(x) < -0.1) : 
            x /= 10
    return x        

In [14]:
epochtimes = 200000
mini_batch = 8
bestloss1 = 1e30 #Mini Batch Loss
preloss = 1e30   #decay the learning rate
start = time.time()

for epoch in range(epochtimes):
    X_train_random = []
    Y_train_random = []
    for i in range(mini_batch):
        rindex = random.randint(0,len(X_train)-1)
        X_train_random.append(X_train[rindex,:])
        Y_train_random.append(Y_train[rindex,:])
    X_train_random = np.array(X_train_random)
    Y_train_random = np.array(Y_train_random)
    
        
    input_hidden = np.dot(X_train_random, weight_hidden) 
    output_hidden = ReLU(input_hidden)
    
    input_hidden2 = np.dot(output_hidden, weight_hidden2) 
    output_hidden2 = ReLU(input_hidden2)
    input_hidden3 = np.dot(output_hidden2, weight_hidden3) 
    output_hidden3 = ReLU(input_hidden3)
    input_hidden4 = np.dot(output_hidden3, weight_hidden4) 
    output_hidden4 = ReLU(input_hidden4)
    input_hidden5 = np.dot(output_hidden4, weight_hidden5) 
    output_hidden5 = ReLU(input_hidden5)
    input_op = np.dot(output_hidden5, weight_output)
    output_op = ReLU(input_op)
    
    
    
    #==========================================
    
    derror_douto = output_op - Y_train_random
    douto_dino = ReLU_der(input_op)
    dino_dwo = output_hidden5      
    derror_dwo = np.dot(dino_dwo.T, derror_douto * douto_dino)
    
    #==========================================
    
    derror_dino = derror_douto * douto_dino
    dino_douth5 = weight_output
    derror_douth5 = np.dot(derror_dino, dino_douth5.T)
    douth5_dinh5 = ReLU_der(input_hidden5)
    dinh5_dwh5 = output_hidden4
    derror_dwh5 = np.dot(dinh5_dwh5.T, douth5_dinh5 * derror_douth5)
    
    #==========================================
    
    derror_dinh5 = derror_douth5 * douth5_dinh5
    dinh5_douth4 = weight_hidden5
    derror_douth4 = np.dot(derror_dinh5, dinh5_douth4.T)
    douth4_dinh4 = ReLU_der(input_hidden4)
    dinh4_dwh4 = output_hidden3
    derror_dwh4 = np.dot(dinh4_dwh4.T, douth4_dinh4 * derror_douth4)
    
    #==========================================
    
    derror_dinh4 = derror_douth4 * douth4_dinh4
    dinh4_douth3 = weight_hidden4
    derror_douth3 = np.dot(derror_dinh4, dinh4_douth3.T)
    douth3_dinh3 = ReLU_der(input_hidden3)
    dinh3_dwh3 = output_hidden2
    derror_dwh3 = np.dot(dinh3_dwh3.T, douth3_dinh3 * derror_douth3)
    
    #==========================================
    
    derror_dinh3 = derror_douth3 * douth3_dinh3
    dinh3_douth2 = weight_hidden3
    derror_douth2 = np.dot(derror_dinh3, dinh3_douth2.T)
    douth2_dinh2 = ReLU_der(input_hidden2)
    dinh2_dwh2 = output_hidden
    derror_dwh2 = np.dot(dinh2_dwh2.T, douth2_dinh2 * derror_douth2)
    
    #==========================================
    
    derror_dinh2 = derror_douth2 * douth2_dinh2
    dinh2_douth = weight_hidden2
    derror_douth = np.dot(derror_dinh2, dinh2_douth.T)
    douth_dinh = ReLU_der(input_hidden)
    dinh_dwh = X_train_random
    derror_dwh = np.dot(dinh_dwh.T, douth_dinh * derror_douth)
    
    #==========================================
       
    
    
    weight_hidden = weight_hidden - limit(lr * derror_dwh)
    weight_hidden2 = weight_hidden2 - limit(lr * derror_dwh2)
    weight_hidden3 = weight_hidden3 - limit(lr * derror_dwh3)
    weight_hidden4 = weight_hidden4 - limit(lr * derror_dwh4)
    weight_hidden5 = weight_hidden5 - limit(lr * derror_dwh5)
    weight_output = weight_output - limit(lr * derror_dwo)
    
    
    error_out = ((1 / 2) * (np.power((output_op - Y_train_random), 2)))
    #print(error_out.sum())
    
        
        
    #calulate error 
    if epoch % 200 == 0 : 
        input_hidden = np.dot(X_train, weight_hidden) 
        output_hidden = ReLU(input_hidden)
        input_hidden2 = np.dot(output_hidden, weight_hidden2) 
        output_hidden2 = ReLU(input_hidden2)
        input_hidden3 = np.dot(output_hidden2, weight_hidden3) 
        output_hidden3 = ReLU(input_hidden3)
        input_hidden4 = np.dot(output_hidden3, weight_hidden4) 
        output_hidden4 = ReLU(input_hidden4)
        input_hidden5 = np.dot(output_hidden4, weight_hidden5) 
        output_hidden5 = ReLU(input_hidden5)
        input_op = np.dot(output_hidden5, weight_output)
        output_op = ReLU(input_op)
        error_out = ((1 / 2) * (np.power((output_op - Y_train), 2)))  
            
        if error_out.sum() > preloss :
            lr *= 0.95
        preloss = error_out.sum()  
        
        print('now training ',epoch*100/epochtimes,'%')
        print(error_out.sum())
        #print(error_out)
        #print('\n',lr * derror_dwh,'\n', lr * derror_dwo,'\n')
        
       
    #print(derror_wh, derror_wo)
end = time.time()

now training  0.0 %
54.342270935686486
now training  0.1 %
18.510098377059876
now training  0.2 %
7.951528413111361
now training  0.3 %
6.253848306119536
now training  0.4 %
6.5173321790486485
now training  0.5 %
4.855494455099366
now training  0.6 %
4.020714917454211
now training  0.7 %
3.4114827255474003
now training  0.8 %
2.9111341976136877
now training  0.9 %
2.8360791446579117
now training  1.0 %
2.2980903234398657
now training  1.1 %
2.1100898654808735
now training  1.2 %
1.8763593256607976
now training  1.3 %
1.868916717920387
now training  1.4 %
1.5358620113598598
now training  1.5 %
1.476662718135873
now training  1.6 %
1.725786834330309
now training  1.7 %
1.2895755469808263
now training  1.8 %
1.2573840577784816
now training  1.9 %
1.4260103798475936
now training  2.0 %
1.1639914753443117
now training  2.1 %
1.039380798920618
now training  2.2 %
1.1499437647551716
now training  2.3 %
0.9511595284545573
now training  2.4 %
1.1688229421538443
now training  2.5 %
0.93286978232

now training  20.9 %
0.5132891751380224
now training  21.0 %
0.5132597815864295
now training  21.1 %
0.5132472256763594
now training  21.2 %
0.513230487835084
now training  21.3 %
0.5132097966389767
now training  21.4 %
0.5131983063807646
now training  21.5 %
0.5131901086422637
now training  21.6 %
0.5131994355581154
now training  21.7 %
0.5131931653942957
now training  21.8 %
0.5131850086840659
now training  21.9 %
0.513184653836662
now training  22.0 %
0.5131793992633278
now training  22.1 %
0.5131854231435987
now training  22.2 %
0.513167929072296
now training  22.3 %
0.513162057454697
now training  22.4 %
0.51314548237154
now training  22.5 %
0.5131416264658509
now training  22.6 %
0.5131345570412141
now training  22.7 %
0.5131282010607526
now training  22.8 %
0.5131235053869833
now training  22.9 %
0.5131214270958092
now training  23.0 %
0.513117264085464
now training  23.1 %
0.5131125880517113


KeyboardInterrupt: 

In [16]:
#print(weight_hidden)
print(lr * derror_dwh)
print(lr * derror_dwh2)
print(lr * derror_dwh3)
print(lr * derror_dwh4)
print(lr * derror_dwh5)
print(lr * derror_dwo)
print("Elapsed (with compilation) = %s" % (end - start))

[[3.566200765686286e-09 -1.7429297995137973e-09 -1.8780655543412932e-08
  ... -2.621587379409494e-10 1.8147968757844272e-09
  -3.0887833949948896e-10]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]
 [3.5642676345626742e-09 -1.7398703952368523e-09 -1.8493374484420203e-08
  ... -2.5783475775167645e-10 1.818452542789002e-09
  -3.0326311273428826e-10]
 ...
 [2.244823098150335e-09 1.092492019477202e-09 -6.775087177674219e-09 ...
  -6.201487905509645e-11 -1.7180255207006156e-09 -8.879984240018694e-11]
 [9.137016633104483e-10 -1.646059276301045e-09 -9.860947567782847e-09 ...
  -1.465662068839964e-10 1.9501083954660505e-09 -1.482280956091283e-10]
 [2.659696621989893e-09 1.205675748100872e-09 -8.630815641133439e-09 ...
  -8.029942013749166e-11 -1.9367196710510503e-09 -1.0668802814643452e-10]]
[[1.8451108632251271e-09 1.4990259522133619e-10 4.862696644671096e-13 ...
  -1.3159793232405083e-09 9.190811057706077e-12 3.196716130974016e-10]
 [-3.14651864515696e-10 -1.0628290103344016e-11 1.2050863854861e-12 ...
  3.

NameError: name 'end' is not defined

In [17]:
single_point = np.array(X_train)
result1 = np.dot(single_point, weight_hidden)
result2 = ReLU(result1)
result3 = np.dot(result2, weight_hidden2)
result4 = ReLU(result3)
result5 = np.dot(result4, weight_hidden3)
result6 = ReLU(result5)
result7 = np.dot(result6, weight_hidden4)
result8 = ReLU(result7)
result9 = np.dot(result8, weight_hidden5)
result10 = ReLU(result9)
result11 = np.dot(result10, weight_output)
result12 = ReLU(result11)
#print(result12)
#print(Y_train_random)
error_out = ((1/len(Y_train)) * (np.power((result12 - Y_train), 2)))
#print(error_out)
print(error_out.sum())

0.003665061415010308


In [18]:
single_point = np.array(X_test)
result1 = np.array(np.dot(single_point, weight_hidden), dtype = np.float )
result2 = ReLU(result1)
result3 = np.array(np.dot(result2, weight_hidden2), dtype = np.float )
result4 = ReLU(result3)
result5 = np.array(np.dot(result4, weight_hidden3), dtype = np.float )
result6 = ReLU(result5)
result7 = np.array(np.dot(result6, weight_hidden4), dtype = np.float )
result8 = ReLU(result7)
result9 = np.array(np.dot(result8, weight_hidden5), dtype = np.float )
result10 = ReLU(result9)
result11 = np.array(np.dot(result10, weight_output), dtype = np.float )
result12 = ReLU(result11)
print(result12)
print(Y_test)
print(len(X_test))
error_out = ((1/len(X_test)) * (np.power((result12 - Y_test), 2)))
print(math.sqrt(error_out.sum()))

[[ 6.87954086e-01]
 [ 9.83924495e-01]
 [ 8.92063090e-01]
 [ 9.65720949e-01]
 [ 2.14416410e-01]
 [ 1.01467068e+00]
 [-2.49431528e-03]
 [-1.20722218e-04]
 [ 1.01464735e+00]
 [ 9.70698361e-01]
 [-1.24641243e-03]
 [-1.31740138e-03]
 [ 1.04707058e+00]
 [-9.17969564e-04]
 [ 9.90399031e-01]
 [ 1.03755309e+00]
 [ 9.78691716e-01]
 [ 1.22296959e+00]
 [ 1.02181430e+00]
 [ 5.58355051e-01]
 [ 1.19906537e+00]
 [ 1.12365652e+00]
 [ 1.04530114e+00]
 [ 1.29632026e+00]
 [ 7.94258253e-01]
 [-5.59956176e-03]
 [-4.69200532e-03]
 [ 3.32417664e-01]
 [-5.29427118e-04]
 [-1.72817741e-03]
 [ 9.93157391e-01]
 [ 9.48957579e-01]
 [ 1.02590147e+00]
 [ 9.84630120e-01]
 [-1.36668590e-03]
 [-3.03370169e-03]
 [-1.84963106e-03]
 [-9.26873940e-04]
 [ 1.99991467e-01]
 [ 9.56344749e-01]
 [ 9.85186546e-01]
 [ 9.80830228e-01]
 [ 1.00297107e+00]
 [ 7.36648956e-01]
 [-1.19374586e-03]
 [ 9.28785240e-01]
 [-2.64875672e-03]
 [ 1.17441074e+00]
 [ 9.30307692e-01]
 [ 1.04147724e+00]
 [ 9.25904427e-01]
 [ 1.00118704e+00]
 [ 8.4517011

In [ ]:
single_point = np.array(X_train)
result1 = np.dot(single_point, mbwh1)
result2 = ReLU(result1)
result3 = np.dot(result2, mbwh2)
result4 = ReLU(result3)
result5 = np.dot(result4, mbwh3)
result6 = ReLU(result5)
result7 = np.dot(result6, mbwh4)
result8 = ReLU(result7)
result9 = np.dot(result8, mbwh5)
result10 = ReLU(result9)
result11 = np.dot(result10, mbwo)
result12 = ReLU(result11)
print("bestloss1 = ", bestloss1)
#print(result12)
#print(Y_train_random)
error_out = ((1/len(Y_train)) * (np.power((result12 - Y_train), 2)))
print(error_out.sum())